version: '3'

services:
  front_end:
    container_name: mini_project_fe
#    image: ducnv/mini_project_fe:latest
    build:
      context: ./front_end
      dockerfile: Dockerfile
    volumes:
      - './front_end:/app/front_end'
      - './front_end/node_modules:/app/front_end/node_modules'
    ports:
      - '1500:1500'
    expose:
      - 1500
    command: ['npm', 'run', 'serve', '--', '--port', '1500']

  backend:
    container_name: mini_project_be
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app/backend'
    ports:
      - '1600:1600'
    depends_on:
      - db
    entrypoint: [ 'poetry', 'run' ]
    command: [ 'uvicorn', 'main:app', '--reload', '--host', '0.0.0.0', '--port', '1600' ]

  db:
    container_name: mini_project_db
    image: postgres:14
    ports:
      - '1700:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
